name: pg
channels:
  - gimli
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - metis
  - numpy
  - openblas
  - pgcore
  - pip
  - pygimli=1.3.1
  - pyvista=0.34.2
  - scipy
  - setuptools